services:
  - type: web
    name: cabease
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: cabease-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cabease-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: cabease-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: cabease-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cabease-db
          property: password
      - key: GOOGLE_AI_API_KEY
        value: AIzaSyBRAMqAbONdk_8AUEbmuniEl5Cy9vOaUOM
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: SPRING_MAIL_USERNAME
        value: tejo.singaporeserver@gmail.com
      - key: SPRING_MAIL_PASSWORD
        sync: false

databases:
  - name: cabease-db
    plan: free
    databaseName: cabease
    user: cabease
